### PR TITLE
add import Variable.Global 1.0

### PR DESCRIPTION
**Pull request by Toine-ddt**

### CODE REVIEW

**Review by jcelerier — COMMENTED** [review]
what is that for ?

**Comment by Toine-ddt** [comment]
it is to use Skin."color"

**Comment by jcelerier** [comment]
hm, does that mean that the program is broken without that PR ?

**Comment by Toine-ddt** [comment]
not brocken, but the color displayed for impulse buttons is wrong (white instead of yellow)

**Comment by jcelerier** [comment]
oh okay. yay for weak type systems

**Pull request merged**
