### PR TITLE
Feature/position #35

### PR DESCRIPTION
**Pull request by Toine-ddt**

### CODE REVIEW

**Comment by jcelerier** [comment]
What I'd recommend: 

1. Read https://git-scm.com/book/fr/v2/Utilitaires-Git-R%C3%A9%C3%A9crire-l%E2%80%99historique
2. `git checkout feature/position`
3. `git rebase -i 4e22cf8 `
4. Squash all the commits
5. Remove the conflicting change in src/WebSocket/ScoreWebSocket.qml (maybe something like `git checkout  main src/WebSocket/ScoreWebSocket.qml` is enough)
6. `git commit --amend`
7. `git push --force`

**Comment by Toine-ddt** [comment]
I am working on it

**Comment by Toine-ddt** [comment]
I have done what you had recommended @jcelerier 
but there are still conflicts. so what commands can I use to resolve them efficiently ?

**Comment by jcelerier** [comment]
weird, it looks like the feature/position was already pushed to main no ?

**Comment by Toine-ddt** [comment]
ah yes ! but I don't know how and when ?

**Comment by jcelerier** [comment]
a mistery for another day :) let's close that pr since it's already merged

**Comment by Toine-ddt** [comment]
I had made new modifications, I am going to make a new PR

**Pull request closed without merging**
